version: "3"

services:
    dojo:
        image: appsecframework/dojo
        container_name: dojo
        ports:
            - "8000:8000"
        volumes:
            - django-DefectDojo:/django-DefectDojo
        env_file:
            - ./env/common.env
            - ./env/dojo.env
    jenkins:
        image: appsecframework/jenkins
        container_name: jenkins
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
    django-DefectDojo: {}
