!!appsecframework.Project {
  customScan: true,
  dockerRepo: appsecframework/dvwa-nologin,
  gitRepo: '',
  imported: true,
  lastScanDate: Apr 9 2019,
  name: DVWA,
  pastScanResultPath: '',
  platform: Web Application,
  reportPath: /home/earthpatipon/Desktop/scanresult/,
  scanEventList: [
    {
      engagementId: -1,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '1552298339349',
      scanResultList: [
        {
          scanName: Normal Scan,
          scanResultDirectory: /home/erbazz/Desktop/scanresult/,
          scanResultFileName: dvwa.xml0,
          scanType: Normal Scan
        }]
      ,
      scanStartDate: '1552298339349'
    },
    {
      engagementId: 18,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '2019-03-11',
      scanResultList: [
        {
          scanName: Normal Scan,
          scanResultDirectory: /home/erbazz/Desktop/scanresult/,
          scanResultFileName: dvwa.xml1,
          scanType: Normal Scan
        }]
      ,
      scanStartDate: '2019-03-11'
    },
    {
      engagementId: 19,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '2019-03-11',
      scanResultList: [
        {
          scanName: Normal Scan,
          scanResultDirectory: /home/erbazz/Desktop/scanresult/,
          scanResultFileName: DVWAOWASP ZapNormalScan2xml,
          scanType: Normal Scan
        }]
      ,
      scanStartDate: '2019-03-11'
    },
    {
      engagementId: 20,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '2019-03-12',
      scanResultList: [
        {
          scanName: Normal Scan,
          scanResultDirectory: /home/erbazz/Desktop/scanresult/,
          scanResultFileName: DVWA_OWASPZap.xml,
          scanType: Normal Scan
        }]
      ,
      scanStartDate: '2019-03-12'
    },
    {
      engagementId: 14,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '2019-03-12',
      scanResultList: [
        {
          scanName: Normal Scan,
          scanResultDirectory: /home/erbazz/Desktop/scanresult/,
          scanResultFileName: DVWA_OWASPZap.xml,
          scanType: Normal Scan
        }]
      ,
      scanStartDate: '2019-03-12'
    },
    {
      engagementId: 15,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '2019-03-12',
      scanResultList: [
        {
          scanName: Normal Scan,
          scanResultDirectory: /home/erbazz/Desktop/scanresult/,
          scanResultFileName: DVWA_OWASPZap.xml,
          scanType: Normal Scan
        }]
      ,
      scanStartDate: '2019-03-12'
    },
    {
      engagementId: 16,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '2019-03-12',
      scanResultList: [
        {
          scanName: ZAP Scan,
          scanResultDirectory: /home/erbazz/Desktop/scanresult/,
          scanResultFileName: DVWA_OWASPZap.xml,
          scanType: ZAP Scan
        }]
      ,
      scanStartDate: '2019-03-12'
    },
    {
      engagementId: -1,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '2019-03-13',
      scanResultList: [
        {
          scanName: ZAP Scan,
          scanResultDirectory: /home/erbazz/Desktop/scanresult/,
          scanResultFileName: DVWA_OWASPZap.,
          scanType: ZAP Scan
        }]
      ,
      scanStartDate: '2019-03-13'
    },
    {
      engagementId: -1,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '2019-04-09',
      scanResultList: [
        {
          scanName: ZAP Scan,
          scanResultDirectory: /home/earthpatipon/Desktop/scanresult/,
          scanResultFileName: DVWA_OWASPZap.xml,
          scanType: ZAP Scan
        },
        {
          scanName: Full Scan,
          scanResultDirectory: /home/earthpatipon/Desktop/scanresult/,
          scanResultFileName: DVWA_Arachni.xml,
          scanType: Full Scan
        },
        {
          scanName: Converter,
          scanResultDirectory: /home/earthpatipon/Desktop/scanresult/,
          scanResultFileName: DVWA_Arachni.xml,
          scanType: Converter
        }]
      ,
      scanStartDate: '2019-04-09'
    },
    {
      engagementId: -1,
      imported: false,
      projectName: DVWA,
      projectPlatform: Web Application,
      scanFinishDate: '2019-04-09',
      scanResultList: [
        {
          scanName: ZAP Scan,
          scanResultDirectory: /home/earthpatipon/Desktop/scanresult/,
          scanResultFileName: DVWA_OWASPZap.xml,
          scanType: ZAP Scan
        },
        {
          scanName: Full Scan,
          scanResultDirectory: /home/earthpatipon/Desktop/scanresult/,
          scanResultFileName: DVWA_Arachni.xml,
          scanType: Full Scan
        },
        {
          scanName: Converter,
          scanResultDirectory: /home/earthpatipon/Desktop/scanresult/,
          scanResultFileName: DVWA_Arachni.xml,
          scanType: Converter
        }]
      ,
      scanStartDate: '2019-04-09'
    }]
  ,
  scanList: [
    {
      scanName: ZAP Scan,
      tool: {
        dockerOptions: null,
        scanScript: {
          ZAP Scan: 'docker run --rm -v {{SCAN_RESULT_DIRECTORY}}:/zap/wrk/:rw -t
            owasp/zap2docker-weekly zap-baseline.py -t {{SCAN_TARGET_URL}} -x {{SCAN_RESULT_FILE}}'
        },
        startScript: null,
        stopScript: null,
        toolDockerRepo: owasp/zap2docker-weekly,
        toolGitRepo: null,
        toolName: OWASP Zap,
        toolPath: null,
        toolReportExtension: xml,
        toolSource: Docker,
        toolType: Web Application
      }
    },
    {
      scanName: Full Scan,
      tool: &id001 {
        dockerOptions: null,
        scanScript: {
          Full Scan: 'docker run --rm -v {{SCAN_RESULT_DIRECTORY}}:/arachni/reports
            ahannigan/docker-arachni bin/arachni {{SCAN_TARGET_URL}} --report-save-path=reports/report.afr',
          Converter: 'docker run --rm -v {{SCAN_RESULT_DIRECTORY}}:/arachni/reports
            ahannigan/docker-arachni bin/arachni_reporter reports/report.afr --reporter=json:outfile=reports/{{SCAN_RESULT_FILE}}'
        },
        startScript: null,
        stopScript: null,
        toolDockerRepo: ahannigan/docker-arachni,
        toolGitRepo: null,
        toolName: Arachni,
        toolPath: null,
        toolReportExtension: xml,
        toolSource: Docker,
        toolType: Web Application
      }
    },
    {
      scanName: Converter,
      tool: *id001
    }]
  ,
  scanStatus: Success,
  source: Docker,
  sourcePath: '',
  urlPort: '10.0.2.15:80'
}
--- !!appsecframework.Project {
  customScan: false,
  dockerRepo: test,
  gitRepo: '',
  imported: false,
  lastScanDate: '-',
  name: test,
  pastScanResultPath: '',
  platform: Web Application,
  reportPath: test,
  scanEventList: [
    ],
  scanList: [
    ],
  scanStatus: Not Started,
  source: Docker,
  sourcePath: '',
  urlPort: '10.0.2.15:80'
}
